import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generateInvoicePDF = (invoice) => {
  const doc = new jsPDF();

  const formatMoney = (amount) => {
    return `Rs. ${Number(amount || 0).toLocaleString()}`;
  };

  const formatDate = (date) => {
    if (!date) return "-";
    return new Date(date).toLocaleDateString();
  };

  const invoiceNumber = invoice.invoiceNumber || "INV-00000";
  const customer = invoice.customer || {};

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 42, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("BizFlow CRM", 14, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Business Management Suite", 14, 26);

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 160, 18);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(invoiceNumber, 160, 26);

  doc.setTextColor(15, 23, 42);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Bill To", 14, 55);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(customer.name || "Unknown Customer", 14, 63);
  doc.text(customer.company || "-", 14, 70);
  doc.text(customer.email || "-", 14, 77);
  doc.text(customer.phone || "-", 14, 84);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Invoice Details", 140, 55);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Invoice No: ${invoiceNumber}`, 140, 63);
  doc.text(`Due Date: ${formatDate(invoice.dueDate)}`, 140, 70);
  doc.text(`Status: ${invoice.status || "draft"}`, 140, 77);

  const tableRows =
    invoice.items?.map((item, index) => {
      const quantity = Number(item.quantity || 0);
      const price = Number(item.price || 0);
      const lineTotal = quantity * price;

      return [
        index + 1,
        item.name || "-",
        item.description || "-",
        quantity,
        formatMoney(price),
        formatMoney(lineTotal),
      ];
    }) || [];

  autoTable(doc, {
    startY: 98,
    head: [["#", "Item", "Description", "Qty", "Price", "Total"]],
    body: tableRows,
    theme: "grid",
    headStyles: {
      fillColor: [15, 23, 42],
      textColor: [255, 255, 255],
      fontStyle: "bold",
    },
    styles: {
      fontSize: 9,
      cellPadding: 3,
    },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 38 },
      2: { cellWidth: 55 },
      3: { cellWidth: 18, halign: "center" },
      4: { cellWidth: 32, halign: "right" },
      5: { cellWidth: 32, halign: "right" },
    },
  });

  const finalY = doc.lastAutoTable.finalY + 12;

  const subtotal = Number(invoice.subtotal || 0);
  const discount = Number(invoice.discount || 0);
  const tax = Number(invoice.tax || 0);
  const grandTotal = Number(invoice.grandTotal || 0);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");

  doc.text("Subtotal:", 140, finalY);
  doc.text(formatMoney(subtotal), 190, finalY, { align: "right" });

  doc.text("Discount:", 140, finalY + 8);
  doc.text(`- ${formatMoney(discount)}`, 190, finalY + 8, {
    align: "right",
  });

  doc.text("Tax:", 140, finalY + 16);
  doc.text(`+ ${formatMoney(tax)}`, 190, finalY + 16, {
    align: "right",
  });

  doc.setDrawColor(226, 232, 240);
  doc.line(140, finalY + 22, 190, finalY + 22);

  doc.setFontSize(13);
  doc.setFont("helvetica", "bold");
  doc.text("Grand Total:", 140, finalY + 31);
  doc.text(formatMoney(grandTotal), 190, finalY + 31, {
    align: "right",
  });

  if (invoice.notes) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Notes", 14, finalY + 45);

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(invoice.notes, 14, finalY + 53, {
      maxWidth: 120,
    });
  }

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(
    "Thank you for doing business with us.",
    14,
    285
  );

  doc.text(
    "Generated by BizFlow CRM",
    196,
    285,
    { align: "right" }
  );

  doc.save(`${invoiceNumber}.pdf`);
};